!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 3
no bgp ebgp-requires-policy
! no bgp network import-check (not needed for this lab)
neighbor 4.4.4.20 remote-as 2
neighbor 4.4.4.20 description Router 2 of AS2
!
network 5.5.5.0/24
