LAB_DESCRIPTION="Simple peering between two BGP routers"
LAB_VERSION=2.0
LAB_AUTHOR="T. Caiazzi, G. Di Battista, M. Patrignani, M. Pizzonia, F. Ricci, M. Rimondini"
LAB_EMAIL=contact@kathara.org
LAB_WEB=http://www.kathara.org/

router1[0]="B"
router1[1]="A"
router1[image]="kathara/frr"

h1[0]="B"
h1[image]="kathara/base"

router2[0]="A"
router2[1]="C"
router2[2]="D"
router2[image]="kathara/frr"

h2[0]="C"
h2[image]="kathara/base"

router3[0]="D"
router3[1]="E"
router3[image]="kathara/frr"

h3[0]="E"
h3[image]="kathara/base"
